name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set required status check
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh api "/repos/elavertu9/Test/branches/main/protection" -f required_status_checks='{[contexts:"lint"]}'

