name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: lint 
    runs-on: ubuntu-latest
    steps:
      - name: Set required status check
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh api "/repos/elavertu9/Test/statuses/${{ github.event.pull_request.head.sha }}" \
          -f context="lint" \
          -f state="pending"
      
      - name: Checkout code
        uses: actions/checkout@v2
        
        
      - name: Run Super-Linter
        uses: github/super-linter@v3.17.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ github.token }}

