name: Test File Extraction

on:
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        working-directory: docker
        run: ./build-image.sh
        
      - name: Start containers
        run: docker-compose -f "docker/docker-compose.yml" up -d
        
#       - name: Copy test file out of container
#         run: docker cp testing-github-actions-container:/tmp/test.txt .
      - name: Inspect docker volume
        run: docker volume inspect docker_test-vol
        
#       - name: Upload test results as GitHub Artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: test-results
#           path: test.txt
