name: Test File Extraction

on:
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Docker Image
        working-directory: docker
        run: ./build-image.sh
        
#       - name: Copy test file out of container
#         run: 
      
      - name: Print working directory and contents
        run: |
          pwd
          ls
