name: Test File Extraction

on:
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Docker Image
        working-directory: docker
        run: ./build-image.sh
        
      - name: Start containers
        run: docker-compose -f "docker/docker-compose.yml" up -d
        
      - name: Copy test file out of container
        run: docker cp testing-github-actions-container:/tmp/test.txt .
      
      - name: Print working directory and contents
        run: |
          pwd
          ls
